on: [push]
jobs:
  hello_to_job:
    runs-on: ubuntu-latest
    name: greet
    steps:
      - name: hello world action flow
        uses: leftoverzzz/test-action1@v2.2
        id: hello
        with:
          username: 'zwc'
      - name : output from hello step    
        run: echo "${{steps.hello.output.time}}"
